spring:
  data:
    mongodb:
     # uri: mongo-uri
server:
  port: 8082
  address: 0.0.0.0

app:
  jwt:
    secret: UrkXxbKiOVfLOr9PnUhIXpJPft70sMUt  # use at least 32 chars
    expiration-ms: 360000000 # 1 hour


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
